### ISSUE TITLE
Crash when loading in while on a space station on 1.12.2

### ISSUE THREAD

**Issue by YellerFeller** [PyrrhaDevs/Galacticraft-RPC#16]
**Describe the bug**
Minecraft crashses when loading a world or entering a server with this mod while in a space station dimension

**To Reproduce**
1. Go to a space station
2. Log out/save and quit
3. Log back in/load world

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1909
 - Minecraft Version: 1.12.2
 - Version: 1.12.2-2.1.1

**Additional context**
Crashes with error: "java.lang.StringIndexOutOfBoundsException: String index out of range: -2"

Galaticraft Info:
- MicdoodleCore-1.12.2-4.0.2.244
- GalacticraftCore-1.12.2-4.0.2.244
- Galacticraft-Planets-1.12.2-4.0.2.244

Crash Report:
[crash-2020-02-24_17.53.44-client.txt](https://github.com/JoeZwet/Galacticraft-RPC/files/4247434/crash-2020-02-24_17.53.44-client.txt)

**Comment by feldim2425** [comment]
This seems to be the case with all modded dimensions that aren't a celestial body from Galaticraft. DeepDark from Extra Utilities and Twilight Forest crash in the same way when entering the dimension.
