### ISSUE TITLE
Crash When Going Through Aroma's Dimensional World Portal

### ISSUE THREAD

**Issue by janagyjr** [PyrrhaDevs/Galacticraft-RPC#17]
**Describe the bug**
Client freezes and then crashes when trying to go through a portal for Aroma1997s Dimensional World

**To Reproduce**
1. Make a modpack
2. Install [these mods](https://github.com/BooLaLaEnterprises/TCGs-Just-for-Fun-Pack/blob/master/Changelog/proposed.md)
3. Make and go through Aroma's dimensional world portal to mining dimension
4. Crash

**Expected behavior**
Clean portal transition into mining dimension.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Minecraft Version 1.12.2
 - Forge Version 14.23.5.2847
- Mod Version 2.2.1

**Additional context**
Crash log here:
https://gist.github.com/janagyjr/9d6ad30fd2c63d0a22c2db186b2a9cd3

**Comment by JustPyrrha** [comment]
Same crash as #16. This will be fixed in the next release.

**Comment by janagyjr** [comment]
Sorry, didn't realize this was a dupe, should've looked closer at issues.

**Comment by JustPyrrha** [comment]
it's alright, ill just close both when I release the fix.

**Comment by janagyjr** [comment]
Thank you so much! I look forward to being able to update the pack soon. Unfortunately I have an unexpected mod replacement or removal decision that's blocking an update.
