### ISSUE TITLE
Being able to change the "Playing ________" in config

### ISSUE THREAD

**Issue by mechobree** [PyrrhaDevs/Galacticraft-RPC#18]
Just a small suggestion, but it would be nice to be able to change what it says in the playing tag for people who play private modpacks.

like for example an option where it has

`"playing_text": "Galacticraft"`

inside the config as the default and you are able to change it to whatever you like and have it show up on discord 

`"playing_text": "in space" `

![Discord_03-05-2020-10 40](https://user-images.githubusercontent.com/29335214/80919284-244d8800-8d37-11ea-9e9b-437075b081a0.png)

**Comment by JustPyrrha** [comment]
the issue with this is that theres not way to achieve this via the rpc api from what i remember. I'll do a bit of looking around to see if im just being dumb.

**Comment by mechobree** [comment]
Would be a shame if so, good luck though!

**Comment by JustPyrrha** [comment]
Sorry I wasn't able to find a way to do this.
