### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by TherealKiaTEC** [PyrrhaDevs/Galacticraft-RPC#19]
on my server the file is not working why is that and please my you fix this ASAP because i have a private SMP and my friends want the mod on the server. If you need more infomation contact me on discord at KiaTEC#1195

**Comment by JustPyrrha** [comment]
this is a client side only mod, you may be thinking of the base Galacticraft mod which can be found [here](https://micdoodle8.com/mods/galacticraft/downloads).
